#!/bin/bash
echo "Add these to Vercel Environment Variables:"
echo "==========================================="
echo "DATABASE_URL"
echo "NEXTAUTH_SECRET"
echo "AUTH_SECRET"
echo "NEXTAUTH_URL=https://client-flow-sooty.vercel.app"
echo "AUTH_URL=https://client-flow-sooty.vercel.app"
echo "STRIPE_SECRET_KEY"
echo "STRIPE_PRO_PRICE_ID"
echo "RESEND_API_KEY"
echo "RESEND_FROM_EMAIL"
echo "AWS_ACCESS_KEY_ID"
echo "AWS_SECRET_ACCESS_KEY"
echo "S3_BUCKET_NAME"
echo "AWS_REGION"
echo "AWS_ENDPOINT_URL"
echo "UPSTASH_REDIS_REST_URL"
echo "UPSTASH_REDIS_REST_TOKEN"
echo "PUSHER_APP_ID"
echo "PUSHER_KEY"
echo "PUSHER_SECRET"
echo "PUSHER_CLUSTER"
echo "NEXT_PUBLIC_PUSHER_KEY"
echo "NEXT_PUBLIC_PUSHER_CLUSTER"
echo "NEXT_PUBLIC_APP_URL=https://client-flow-sooty.vercel.app"
echo "SEED_SECRET"
echo "NEXT_PUBLIC_SHOW_DEMO_HINT=true"
